apiVersion: v1
kind: Service
metadata:
  name: customer-service  # Name of the service
spec:
  type: NodePort  # Exposes the service to external traffic
  selector:
    app: customer-service  # Ties the service to the pods with this label
  ports:
    - port: 3000  # Port the service will listen on inside the cluster
      targetPort: 3000  # Port on the container to forward the request to
      nodePort: 30085  # Port on the machine to expose (external port)
